# Generated by Django 5.2.14 on 2026-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_post',
        ),
        migrations.RemoveField(
            model_name='report',
            name='post',
        ),
        migrations.AddField(
            model_name='report',
            name='comment_mongo_id',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='report',
            name='post_mongo_id',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
