# Generated by Django 5.2.14 on 2026-06-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_clearedconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearedconversation',
            name='cleared_at',
            field=models.DateTimeField(),
        ),
    ]
