# Generated by Django 5.2.14 on 2026-06-28 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practicesubmission_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceprompt',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
